"""add_foreign_keys

Revision ID: c5637630ca54
Revises: e00d3d299827
Create Date: 2026-02-07 20:57:12.834364

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5637630ca54"
down_revision: str | Sequence[str] | None = "e00d3d299827"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "agent_reasoning", "conversations", ["conversation_id"], ["conversation_id"]
    )
    op.create_foreign_key(
        None, "agent_reasoning", "participants", ["participant_id"], ["participant_id"]
    )
    op.create_foreign_key(
        None, "appointments", "participants", ["participant_id"], ["participant_id"]
    )
    op.create_foreign_key(
        None, "conversations", "participants", ["participant_id"], ["participant_id"]
    )
    op.create_foreign_key(None, "events", "appointments", ["appointment_id"], ["appointment_id"])
    op.create_foreign_key(None, "events", "participants", ["participant_id"], ["participant_id"])
    op.create_foreign_key(
        None, "handoff_queue", "participants", ["participant_id"], ["participant_id"]
    )
    op.create_foreign_key(
        None, "participant_trials", "participants", ["participant_id"], ["participant_id"]
    )
    op.create_foreign_key(None, "rides", "appointments", ["appointment_id"], ["appointment_id"])
    op.create_foreign_key(None, "rides", "participants", ["participant_id"], ["participant_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rides", type_="foreignkey")
    op.drop_constraint(None, "rides", type_="foreignkey")
    op.drop_constraint(None, "participant_trials", type_="foreignkey")
    op.drop_constraint(None, "handoff_queue", type_="foreignkey")
    op.drop_constraint(None, "events", type_="foreignkey")
    op.drop_constraint(None, "events", type_="foreignkey")
    op.drop_constraint(None, "conversations", type_="foreignkey")
    op.drop_constraint(None, "appointments", type_="foreignkey")
    op.drop_constraint(None, "agent_reasoning", type_="foreignkey")
    op.drop_constraint(None, "agent_reasoning", type_="foreignkey")
    # ### end Alembic commands ###
