"""initial_schema

Revision ID: e00d3d299827
Revises: 
Create Date: 2026-02-07 20:51:11.295949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e00d3d299827'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_reasoning',
    sa.Column('reasoning_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('reasoning_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('safety_gate_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('reasoning_id')
    )
    op.create_index(op.f('ix_agent_reasoning_conversation_id'), 'agent_reasoning', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_reasoning_participant_id'), 'agent_reasoning', ['participant_id'], unique=False)
    op.create_table('appointments',
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('trial_id', sa.String(length=100), nullable=False),
    sa.Column('visit_type', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('google_event_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('site_address', sa.String(length=300), nullable=True),
    sa.Column('site_name', sa.String(length=200), nullable=True),
    sa.Column('prep_instructions', sa.Text(), nullable=True),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=True),
    sa.Column('slot_held_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('teach_back_passed', sa.Boolean(), nullable=True),
    sa.Column('teach_back_attempts', sa.Integer(), nullable=False),
    sa.Column('cancellation_reason', sa.String(length=200), nullable=True),
    sa.Column('no_show_reason', sa.String(length=200), nullable=True),
    sa.Column('outcome_reason_code', sa.String(length=50), nullable=True),
    sa.Column('slot_released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('appointment_id'),
    sa.UniqueConstraint('google_event_id')
    )
    op.create_index(op.f('ix_appointments_participant_id'), 'appointments', ['participant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('trial_id', sa.String(length=100), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=True),
    sa.Column('call_sid', sa.String(length=100), nullable=True),
    sa.Column('audio_gcs_path', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('full_transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('handoff_reason', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('conversation_id'),
    sa.UniqueConstraint('call_sid')
    )
    op.create_index(op.f('ix_conversations_participant_id'), 'conversations', ['participant_id'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('trial_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provenance', sa.String(length=20), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_participant_id'), 'events', ['participant_id'], unique=False)
    op.create_index('ix_events_participant_type_created', 'events', ['participant_id', 'event_type', 'created_at'], unique=False)
    op.create_table('handoff_queue',
    sa.Column('handoff_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('trial_id', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommended_next_action', sa.String(length=200), nullable=True),
    sa.Column('coordinator_phone', sa.String(length=20), nullable=True),
    sa.Column('callback_number', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('preferred_callback_window', sa.String(length=50), nullable=True),
    sa.Column('handoff_packet', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('handoff_id')
    )
    op.create_index(op.f('ix_handoff_queue_participant_id'), 'handoff_queue', ['participant_id'], unique=False)
    op.create_table('participant_trials',
    sa.Column('participant_trial_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('trial_id', sa.String(length=100), nullable=False),
    sa.Column('pipeline_status', sa.String(length=20), nullable=False),
    sa.Column('enrollment_status', sa.String(length=20), nullable=False),
    sa.Column('eligibility_status', sa.String(length=20), nullable=False),
    sa.Column('eligibility_confidence', sa.Float(), nullable=True),
    sa.Column('screening_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ehr_discrepancies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('adversarial_recheck_done', sa.Boolean(), nullable=False),
    sa.Column('adversarial_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('participant_trial_id'),
    sa.UniqueConstraint('participant_id', 'trial_id', name='uq_participant_trial')
    )
    op.create_index(op.f('ix_participant_trials_participant_id'), 'participant_trials', ['participant_id'], unique=False)
    op.create_index(op.f('ix_participant_trials_trial_id'), 'participant_trials', ['trial_id'], unique=False)
    op.create_table('participants',
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('mary_id', sa.String(length=64), nullable=False),
    sa.Column('agency_id', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('secondary_phone', sa.String(length=20), nullable=True),
    sa.Column('address_street', sa.String(length=200), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=50), nullable=True),
    sa.Column('address_zip', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('distance_to_site_km', sa.Float(), nullable=True),
    sa.Column('preferred_channel', sa.String(length=20), nullable=True),
    sa.Column('best_time_to_reach', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('identity_status', sa.String(length=20), nullable=False),
    sa.Column('dnc_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contactability', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('caregiver', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contactability_risk', sa.String(length=10), nullable=False),
    sa.Column('outreach_attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_type', sa.String(length=30), nullable=True),
    sa.Column('recheck_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('participant_id')
    )
    op.create_index(op.f('ix_participants_mary_id'), 'participants', ['mary_id'], unique=True)
    op.create_index(op.f('ix_participants_phone'), 'participants', ['phone'], unique=False)
    op.create_table('rides',
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('pickup_address', sa.String(length=300), nullable=False),
    sa.Column('dropoff_address', sa.String(length=300), nullable=False),
    sa.Column('scheduled_pickup_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uber_ride_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('return_trip', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ride_id')
    )
    op.create_index(op.f('ix_rides_appointment_id'), 'rides', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_rides_participant_id'), 'rides', ['participant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rides_participant_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_appointment_id'), table_name='rides')
    op.drop_table('rides')
    op.drop_index(op.f('ix_participants_phone'), table_name='participants')
    op.drop_index(op.f('ix_participants_mary_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_participant_trials_trial_id'), table_name='participant_trials')
    op.drop_index(op.f('ix_participant_trials_participant_id'), table_name='participant_trials')
    op.drop_table('participant_trials')
    op.drop_index(op.f('ix_handoff_queue_participant_id'), table_name='handoff_queue')
    op.drop_table('handoff_queue')
    op.drop_index('ix_events_participant_type_created', table_name='events')
    op.drop_index(op.f('ix_events_participant_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_conversations_participant_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_appointments_participant_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_agent_reasoning_participant_id'), table_name='agent_reasoning')
    op.drop_index(op.f('ix_agent_reasoning_conversation_id'), table_name='agent_reasoning')
    op.drop_table('agent_reasoning')
    # ### end Alembic commands ###
